<a href="https://colab.research.google.com/github/vinayhpandya/onefourthlabscode/blob/master/pytorchintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [0]:
x=torch.ones(3,2)
print(x)
Y=torch.zeros(3,2)
print(Y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [0]:
x=torch.empty(3,2)
print(x)
y=torch.zeros_like(x)
print(y)

tensor([[1.2064e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [0]:
X=torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
print(X)

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])


In [0]:
x=torch.linspace(1,6,steps=5)
print(x)

tensor([1.0000, 2.2500, 3.5000, 4.7500, 6.0000])


In [0]:
X=torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
print(X)

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])


In [0]:
print(X[:,2])
print(X.size())

tensor([3, 5, 7])
torch.Size([3, 3])


In [0]:
y=X[1,2]
print(y)
print(y.item())

tensor(5)
5


#Reshaping

In [0]:
print(X)
Y=X.view(1,9)
print(Y)

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])
tensor([[1, 2, 3, 3, 4, 5, 5, 6, 7]])


In [0]:
print(X.view(9,-1))

tensor([[1],
        [2],
        [3],
        [3],
        [4],
        [5],
        [5],
        [6],
        [7]])


#Tensor operations

In [0]:
x=torch.ones(2,3)
y=torch.ones(2,3)
print(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [0]:
z=y.add(x)
print(y)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [0]:
z=y.add_(x)
print(y)
print(z)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


#numpy vs pytorch

In [0]:
x_np=x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
a=np.random.randn(5,5)
print(a)
a_pt=torch.from_numpy(a)
print(a_pt)

[[-0.58633292 -0.98867042  0.12526125 -0.24885206 -2.68506886]
 [ 0.05412726  2.42986765  0.40722592 -0.37792744 -0.40010229]
 [-1.03878148  0.79798696  0.23485916  1.22410651 -1.81760562]
 [ 1.08471827  0.25331406 -1.99391898  0.35061918 -0.25878707]
 [-1.0920432  -0.36904803  0.83158674  1.19402945  0.04159334]]
tensor([[-0.5863, -0.9887,  0.1253, -0.2489, -2.6851],
        [ 0.0541,  2.4299,  0.4072, -0.3779, -0.4001],
        [-1.0388,  0.7980,  0.2349,  1.2241, -1.8176],
        [ 1.0847,  0.2533, -1.9939,  0.3506, -0.2588],
        [-1.0920, -0.3690,  0.8316,  1.1940,  0.0416]], dtype=torch.float64)


In [0]:
np.add(a,1,out=a)
print(a)
print(a_pt)

[[ 0.41366708  0.01132958  1.12526125  0.75114794 -1.68506886]
 [ 1.05412726  3.42986765  1.40722592  0.62207256  0.59989771]
 [-0.03878148  1.79798696  1.23485916  2.22410651 -0.81760562]
 [ 2.08471827  1.25331406 -0.99391898  1.35061918  0.74121293]
 [-0.0920432   0.63095197  1.83158674  2.19402945  1.04159334]]
tensor([[ 0.4137,  0.0113,  1.1253,  0.7511, -1.6851],
        [ 1.0541,  3.4299,  1.4072,  0.6221,  0.5999],
        [-0.0388,  1.7980,  1.2349,  2.2241, -0.8176],
        [ 2.0847,  1.2533, -0.9939,  1.3506,  0.7412],
        [-0.0920,  0.6310,  1.8316,  2.1940,  1.0416]], dtype=torch.float64)


#Performace

In [0]:
%%time
for k in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=a+b

CPU times: user 82.3 ms, sys: 633 µs, total: 82.9 ms
Wall time: 84.5 ms


In [0]:
%%time
for k in range(100):
  a=torch.randn([100,100])
  b=torch.randn([100,100])
  c=a+b

CPU times: user 20.9 ms, sys: 1.21 ms, total: 22.1 ms
Wall time: 24.5 ms


In [0]:
%%time
for k in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=np.matmul(a,b)

CPU times: user 140 ms, sys: 82.5 ms, total: 223 ms
Wall time: 119 ms


In [0]:
%%time
for k in range(100):
  a=torch.randn([100,100])
  b=torch.randn([100,100])
  c=torch.matmul(a,b)

CPU times: user 44.7 ms, sys: 52.8 ms, total: 97.6 ms
Wall time: 67.2 ms


#Cuda support

In [0]:
print(torch.cuda.device_count())

1


In [0]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [0]:
cuda0=torch.device("cuda:0")

In [0]:
a=torch.ones(3,2,device=cuda0)
b=torch.ones(3,2,device=cuda0)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [0]:
%%time
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  np.add(b, a)

CPU times: user 1min 26s, sys: 1.52 s, total: 1min 28s
Wall time: 1min 28s


In [0]:
%%time
for i in range(10):
  a_cpu = torch.randn([10000, 10000])
  b_cpu = torch.randn([10000, 10000])
  b_cpu.add_(a_cpu)

CPU times: user 18.6 s, sys: 298 ms, total: 18.9 s
Wall time: 18.9 s


In [0]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  b.add_(a)

CPU times: user 2.86 ms, sys: 13.9 ms, total: 16.7 ms
Wall time: 22.1 ms


#Autodiff

In [0]:
x=torch.ones([3,2],requires_grad=True)

In [0]:
y=x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [0]:
z=y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [0]:
t=torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [0]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [0]:
print(y.grad)

None


In [0]:
x=torch.ones([3,2],requires_grad=True)
y=x+5
r=1/(1+torch.exp(-y))
print(r)
s=torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [0]:
x=torch.ones([3,2],requires_grad=True)
y=x+5
r=1/(1+torch.exp(-y))
print(r)
a=torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


#Using pytorch in a neural network

In [0]:
x=torch.randn([20,1],requires_grad=True)
y=3*x+5

In [0]:
w=torch.tensor([1.],requires_grad=True)
b=torch.tensor([1.],requires_grad=True)
y_hat=w*x+b
loss=torch.sum((y_hat-y)**2)

In [0]:
loss

tensor(403.3911, grad_fn=<SumBackward0>)

In [0]:
loss.backward()

In [0]:
print(w.grad,b.grad)

tensor([-73.4137]) tensor([-164.9887])


In [0]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print(w.item(), b.item())

for i in range(10):
  
  x = torch.randn([20, 1])
  y = 3*x - 2
  
  y_hat = w*x + b
  loss = torch.sum((y_hat - y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

  print(w.item(), b.item())

1.0 1.0
1.6134581565856934 -0.17426347732543945
1.8212313652038574 -0.9101713299751282
2.0644943714141846 -1.3328189849853516
2.4291484355926514 -1.532092809677124
2.7663345336914062 -1.690643072128296
2.8588006496429443 -1.8354038000106812
2.9126131534576416 -1.8908089399337769
2.938631772994995 -1.9322959184646606
2.9510457515716553 -1.953632116317749
2.962343215942383 -1.9672083854675293


In [0]:
%%time
learning_rate = 0.01
N=10000
epochs=200


w = torch.randn([N], requires_grad=True,device=cuda0)
b = torch.ones([1], requires_grad=True,device=cuda0)

#print(w.item(), b.item())

for i in range(10):
  
  x = torch.randn([N, 1],device=cuda0)
  y = 3*x - 2
  
  y_hat = w*x + b
  loss = torch.sum((y_hat - y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

  #print(w.item(), b.item())

CPU times: user 7.62 ms, sys: 4.04 ms, total: 11.7 ms
Wall time: 16.9 ms
